---
title: "News Story"
author: "Giovanna Lino"
---

Article published in the George Magazine for the GW Fashion Business Association. The articles talks about the luxury brand Burberry and its strategies on dealing with sustainability and ESG metrics in a more connected world.

**Burberry: the brand\'s dilemma with sustainability**

   The fashion industry is the second largest polluter in the world and consumers are becoming more aware of this. There has been a push to prioritize companies that acknowledge the value of sustainability, and hesitation to support those that fail to address it. Sustainability is a primary concern for consumers and in order for companies to continue to optimize their sales and remain relevant, their designers and managers must address the topic immediately.

   When it comes to sustainability, companies have different opinions. On one hand, some argue that becoming sustainable is too costly and not worth the effort. While on the other hand, some brands view this extra cost as something that will be compensated by new clientele. However, it seems that the vast majority of Millenial, Gen X, Gen Z consumers believe that sustainability is a significant issue and that it should be addressed in the fashion industry. 

   With the influx of these concerned consumers, brands must adjust their strategies and undertake the topic of sustainability to stay competitive. For example, in the luxury fashion industry, fur has always been an important medium. In recent years, there has been a decrease in demand for the luxurious animal by product because there is a heightened awareness of the detrimental effects of the fur industry. For that reason, some designers are beginning to swap fur for something faux. In my opinion, this shift is beneficial and will have a positive impact on a luxury brand\'s reputation.\

   One high end brand that is highly invested in sustainability is Burberry, the British fashion house created in 1865 by Thomas Burberry. The company proved to be unique in the high fashion market when Thomas created Gabardine, a \'breathable, weatherproof and hardwearing fabric revolutionising rainwear\'. Also adding to the originality of the brand is Thomas Burberry\'s creation of the iconic pattern-based scarves, purses, and trench coats. In 2017, when the company\'s annual report was released, environmental activists protested the brand because it had burned almost \$29 million dollars of unsold inventory in a year. With the major repercussion of the brand\'s lack of sustainability commitment, social media backlash, the movement #Burnberry arose to demand change. The protests proved to be effective since Burberry is now dedicated to improving sustainability inside the company.\

   As of now, the brand uses 58% of its energy and 68% of its electricity from clean energy sources and Burberry plans to stay committed to sustainability in the future. The brand has made several promises to become more sustainable for 2022. For instance, Burberry has committed to stopping the use of real fur and burning unwanted items, become carbon neutral by 2022, and operate entirely by renewable energy. In addition, Burberry has released a \'Responsibility Agenda\' to set goals for increasing sustainability within the company. The agenda focuses on three areas: product, company, and communities. Each area is centered on achieving progress by making the brand\'s product more recyclable, ridding the practice of burning unsaleable products, and impacting teachers and students by increasing mentoring programs in developing regions.\

   The \'Responsibility Agenda\' goals abides with the Paris Climate Agreement and the UN\'s 17 Sustainable Development Goals. Burberry committed to becoming a 100% renewable energy run company, and to create a Manufacturing Excellence Program focused on enhancing worker wellbeing in the company\'s supply chain. The brand has been recognized with two awards for its sustainable fashion approach: Leading luxury brand in the 'Textiles, Apparel & Luxury Goods' sector by the DJSI 2018, and \'Bronze Class\' in RobecoSAM\'s 2018 Sustainability Yearbook.\

   Furthermore, Burberry established partnerships aimed at increasing sustainability. First, Burberry collaborated with Elvis & Kresse, a sustainable company devoted to rescuing raw materials and transforming it into luxury accessories, to make 120 tons of wasted leather fabric into selling products. Second, the brand has launched a capsule collection made from Econyl, sustainable nylon made from regenerated fishing nets, fabric scraps and industrial plastic, developing a way to combat plastic waste while creating a circular fashion filled with luxury products.

   Burberry is one example of a company that suffered political turmoil due to its unsustainable approaches to fashion. Now, the brand is fixing the problem by collaborating with sustainable brands, becoming more transparent with its consumers and stakeholders, and setting goals to increase sustainability at the company. My hope is that Burberry becomes an example for other haute couture to follow.

\
